# S1_define_models.R -- generated by JSDMWorkbench
set.seed(1)
library(Hmsc)
localDir <- '.'
dataDir <- file.path(localDir, 'data')
modelDir <- file.path(localDir, 'models')
if (!dir.exists(modelDir)) dir.create(modelDir, recursive = TRUE)
Y <- read.csv(file.path(dataDir, 'Y.csv'), row.names = 1, check.names = FALSE)
XData <- read.csv(file.path(dataDir, 'XData.csv'), row.names = 1, check.names = FALSE, stringsAsFactors = FALSE)
factor_preserve_order <- function(x) { x <- as.character(x); x[trimws(x) == ''] <- NA; factor(x, levels = unique(x[!is.na(x)])) }
clean_types <- function(df) { for (nm in names(df)) { if (is.character(df[[nm]])) { x <- trimws(df[[nm]]); x[x == ''] <- NA; nx <- suppressWarnings(as.numeric(x)); df[[nm]] <- if (all(is.na(x) | !is.na(nx))) nx else factor_preserve_order(x) }; if (is.logical(df[[nm]])) df[[nm]] <- factor_preserve_order(df[[nm]]) }; df }
clean_study <- function(df, n, units, ensure_col) { if (is.null(df)) { df <- data.frame(sample = units, stringsAsFactors = FALSE); rownames(df) <- units }; if (nrow(df) != n) stop('studyDesign.csv rows must match Y rows.'); if (!(ensure_col %in% names(df))) df[[ensure_col]] <- units; for (nm in names(df)) df[[nm]] <- factor_preserve_order(df[[nm]]); df }
select_coord_cols <- function(coord, lon_col, lat_col) { nm <- names(coord); find_col <- function(x) { hit <- nm[tolower(nm) == tolower(x)]; if (length(hit) > 0) hit[1] else NA_character_ }; req <- c(find_col(lon_col), find_col(lat_col)); if (all(!is.na(req))) return(req); for (pair in list(c('longitude','latitude'), c('lon','lat'), c('x','y'), c('easting','northing'))) { hit <- c(find_col(pair[1]), find_col(pair[2])); if (all(!is.na(hit))) return(hit) }; num <- nm[vapply(coord, function(z) all(is.na(z) | !is.na(suppressWarnings(as.numeric(z)))), logical(1))]; if (length(num) >= 2) return(num[1:2]); stop('Coordinate columns not found in coordinates.csv.') }
make_gpp_knots <- function(xy, sKnot_file = '') { if (nzchar(sKnot_file)) { for (path in c(sKnot_file, file.path('data', sKnot_file), file.path('inputs', sKnot_file))) { if (file.exists(path)) { knots <- read.csv(path, row.names = 1, check.names = FALSE); knots <- as.data.frame(knots[, seq_len(min(2, ncol(knots))), drop = FALSE]); knots[] <- lapply(knots, function(z) suppressWarnings(as.numeric(z))); if (nrow(knots) > 0 && ncol(knots) == 2 && all(is.finite(as.matrix(knots)))) return(knots) } } }; n_knots <- max(2L, min(10L, floor(sqrt(nrow(xy))))); knots <- tryCatch(constructKnots(as.data.frame(xy), nKnots = n_knots), error = function(e) NULL); if (is.null(knots) || nrow(knots) == 0) stop('GPP spatial model needs knot locations; automatic constructKnots() failed.'); as.data.frame(knots) }
XData <- clean_types(XData)
Y <- as.matrix(Y); storage.mode(Y) <- 'numeric'
XFormula <- as.formula('~ pH + moisture + canopy + substrate + elevation')
distr <- 'probit'
model_args <- list(Y = Y, XData = XData, XFormula = XFormula, distr = distr)
TrData <- read.csv(file.path(dataDir, 'TrData.csv'), row.names = 1, check.names = FALSE, stringsAsFactors = FALSE)
TrData <- clean_types(TrData)
model_args$TrData <- TrData
model_args$TrFormula <- as.formula('~ life_form + height_mm + reproduction')
random_mode <- 'spatial_full'
group_col <- 'sample'
spatial_method <- 'Full'
longlat <- FALSE
sKnot_file <- ''
if (random_mode == 'sample') {
  studyDesign <- read.csv(file.path(dataDir, 'studyDesign.csv'), row.names = 1, check.names = FALSE, stringsAsFactors = FALSE)
  if (!nzchar(group_col)) group_col <- 'sample'
  units <- if (!is.null(rownames(Y)) && !anyDuplicated(rownames(Y))) rownames(Y) else sprintf('sample_%03d', seq_len(nrow(Y)))
  studyDesign <- clean_study(studyDesign, nrow(Y), units, group_col)
  studyDesign[[group_col]] <- as.factor(studyDesign[[group_col]])
  rL <- HmscRandomLevel(units = levels(studyDesign[[group_col]]))
  model_args$studyDesign <- studyDesign
  model_args$ranLevels <- setNames(list(rL), group_col)
}
if (random_mode %in% c('spatial', 'spatial_full', 'spatial_nngp', 'spatial_gpp')) {
  coord <- read.csv(file.path(dataDir, 'coordinates.csv'), row.names = 1, check.names = FALSE)
  spatial_col <- 'spatial_unit'
  units <- if (!is.null(rownames(coord)) && length(rownames(coord)) == nrow(Y) && !anyDuplicated(rownames(coord))) rownames(coord) else sprintf('spatial_%03d', seq_len(nrow(Y)))
  studyDesign <- if (file.exists(file.path(dataDir, 'studyDesign.csv'))) read.csv(file.path(dataDir, 'studyDesign.csv'), row.names = 1, check.names = FALSE, stringsAsFactors = FALSE) else NULL
  studyDesign <- clean_study(studyDesign, nrow(Y), units, spatial_col)
  studyDesign[[spatial_col]] <- factor(units, levels = units)
  coord_cols <- select_coord_cols(coord, 'longitude', 'latitude')
  xy <- as.matrix(coord[, coord_cols, drop = FALSE]); storage.mode(xy) <- 'numeric'; if (any(!is.finite(xy))) stop('Spatial coordinate columns must be numeric and finite.')
  rownames(xy) <- units
  if (spatial_method == 'NNGP') {
    rL <- HmscRandomLevel(sData = xy, sMethod = 'NNGP', nNeighbours = 10, longlat = longlat)
  } else if (spatial_method == 'GPP') {
    sKnot <- make_gpp_knots(xy, sKnot_file); write.csv(sKnot, file.path(dataDir, 'generated_sKnot_GPP.csv'))
    rL <- HmscRandomLevel(sData = xy, sMethod = 'GPP', sKnot = sKnot, longlat = longlat)
  } else {
    rL <- HmscRandomLevel(sData = xy, sMethod = 'Full', longlat = longlat)
  }
  model_args$studyDesign <- studyDesign
  model_args$ranLevels <- setNames(list(rL), spatial_col)
}
m <- do.call(Hmsc, model_args)
models <- list(main = m)
save(models, file = file.path(modelDir, 'unfitted_models.RData'))
