# S2_fit_models.R -- generated by JSDMWorkbench
set.seed(1)
library(Hmsc)
modelDir <- file.path('.', 'models')
load(file.path(modelDir, 'unfitted_models.RData'))
samples <- 2
thin <- 1
transient <- 1
nChains <- 1
nParallel <- 1
for (mi in seq_along(models)) {
  models[[mi]] <- sampleMcmc(models[[mi]], samples = samples, thin = thin, transient = transient, nChains = nChains, nParallel = nParallel)
}
save(models, file = file.path(modelDir, paste0('models_thin_', thin, '_samples_', samples, '_chains_', nChains, '.Rdata')))
