# S3_evaluate_convergence.R -- generated by JSDMWorkbench
set.seed(1)
library(Hmsc); library(coda)
modelDir <- file.path('.', 'models'); resultDir <- file.path('.', 'results'); tableDir <- file.path('.', 'tables')
if (!dir.exists(resultDir)) dir.create(resultDir, recursive = TRUE)
samples <- 2
thin <- 1
nChains <- 1
load(file.path(modelDir, paste0('models_thin_', thin, '_samples_', samples, '_chains_', nChains, '.Rdata')))
txt <- file.path(resultDir, 'MCMC_convergence.txt'); cat('MCMC convergence diagnostics\n\n', file = txt)
pdf(file.path(resultDir, 'MCMC_convergence.pdf'))
for (j in seq_along(models)) {
  mpost <- convertToCodaObject(models[[j]], spNamesNumbers = c(TRUE, FALSE), covNamesNumbers = c(TRUE, FALSE))
  psrf <- tryCatch(coda::gelman.diag(mpost$Beta, multivariate = FALSE)$psrf[,1], error = function(e) NULL)
  if (!is.null(psrf)) {
    cat('\nModel: ', names(models)[j], '\n', file = txt, append = TRUE)
    cat(capture.output(summary(psrf)), sep='\n', file = txt, append = TRUE)
    hist(psrf, main = paste('PSRF Beta', names(models)[j]), xlab = 'PSRF')
    write.csv(data.frame(parameter = names(psrf), PSRF = as.numeric(psrf)), file.path(tableDir, paste0('S3_beta_psrf_', names(models)[j], '.csv')), row.names = FALSE)
  }
}
dev.off()
