# S4_compute_model_fit.R -- generated by JSDMWorkbench
set.seed(1)
library(Hmsc)
modelDir <- file.path('.', 'models'); tableDir <- file.path('.', 'tables'); predDir <- file.path('.', 'predictions')
samples <- 2
thin <- 1
nChains <- 1
nParallel <- 1
nfolds <- 2
load(file.path(modelDir, paste0('models_thin_', thin, '_samples_', samples, '_chains_', nChains, '.Rdata')))
MF <- list(); MFCV <- list(); WAIC <- list()
for (mi in seq_along(models)) {
  preds <- computePredictedValues(models[[mi]])
  MF[[mi]] <- evaluateModelFit(hM = models[[mi]], predY = preds)
  saveRDS(preds, file.path(predDir, paste0('predicted_values_', names(models)[mi], '.rds')))
  partition <- createPartition(models[[mi]], nfolds = nfolds)
  preds_cv <- computePredictedValues(models[[mi]], partition = partition, nParallel = nParallel)
  MFCV[[mi]] <- evaluateModelFit(hM = models[[mi]], predY = preds_cv)
  WAIC[[mi]] <- tryCatch(computeWAIC(models[[mi]]), error = function(e) e$message)
}
names(MF) <- names(models); names(MFCV) <- names(models); names(WAIC) <- names(models)
save(MF, MFCV, WAIC, file = file.path(modelDir, paste0('MF_thin_', thin, '_samples_', samples, '_chains_', nChains, '_nfolds_', nfolds, '.Rdata')))
