# S5_show_model_fit.R -- generated by JSDMWorkbench
library(Hmsc)
modelDir <- file.path('.', 'models'); resultDir <- file.path('.', 'results')
samples <- 2
thin <- 1
nChains <- 1
nfolds <- 2
load(file.path(modelDir, paste0('MF_thin_', thin, '_samples_', samples, '_chains_', nChains, '_nfolds_', nfolds, '.Rdata')))
pdf(file.path(resultDir, paste0('model_fit_nfolds_', nfolds, '.pdf')))
for (j in seq_along(MF)) {
  cMF <- MF[[j]]; cMFCV <- MFCV[[j]]
  if (!is.null(cMF$TjurR2) && !is.null(cMFCV$TjurR2)) { plot(cMF$TjurR2, cMFCV$TjurR2, xlab='explanatory power', ylab='predictive power', main=paste0(names(MF)[j], ': Tjur R2')); abline(0,1) }
  if (!is.null(cMF$R2) && !is.null(cMFCV$R2)) { plot(cMF$R2, cMFCV$R2, xlab='explanatory power', ylab='predictive power', main=paste0(names(MF)[j], ': R2')); abline(0,1) }
  if (!is.null(cMF$AUC) && !is.null(cMFCV$AUC)) { plot(cMF$AUC, cMFCV$AUC, xlab='explanatory power', ylab='predictive power', main=paste0(names(MF)[j], ': AUC')); abline(0,1) }
}
dev.off()
