# S6_show_parameter_estimates.R -- generated by JSDMWorkbench
library(Hmsc)
if (requireNamespace('corrplot', quietly = TRUE)) library(corrplot)
modelDir <- file.path('.', 'models'); resultDir <- file.path('.', 'results')
samples <- 2
thin <- 1
nChains <- 1
load(file.path(modelDir, paste0('models_thin_', thin, '_samples_', samples, '_chains_', nChains, '.Rdata')))
txt <- file.path(resultDir, 'parameter_estimates.txt'); cat('Parameter estimates\n\n', file=txt)
pdf(file.path(resultDir, 'parameter_estimates.pdf'))
for (j in seq_along(models)) {
  m <- models[[j]]
  VP <- tryCatch(computeVariancePartitioning(m), error=function(e) NULL)
  if (!is.null(VP)) { write.csv(VP$vals, file.path(resultDir, paste0('parameter_estimates_VP_', names(models)[j], '.csv'))); try(plotVariancePartitioning(hM=m, VP=VP, main=paste0('Variance partitioning: ', names(models)[j])), silent=TRUE) }
  postBeta <- tryCatch(getPostEstimate(m, parName='Beta'), error=function(e) NULL)
  if (!is.null(postBeta)) { write.csv(as.data.frame(t(postBeta$mean)), file.path(resultDir, paste0('parameter_estimates_Beta_mean_', names(models)[j], '.csv'))); try(plotBeta(m, post=postBeta, supportLevel=0.95, param='Sign'), silent=TRUE) }
  postGamma <- tryCatch(getPostEstimate(m, parName='Gamma'), error=function(e) NULL)
  if (!is.null(postGamma)) { write.csv(as.data.frame(t(postGamma$mean)), file.path(resultDir, paste0('parameter_estimates_Gamma_mean_', names(models)[j], '.csv'))); try(plotGamma(m, post=postGamma, supportLevel=0.95, param='Sign'), silent=TRUE) }
  OmegaCor <- tryCatch(computeAssociations(m), error=function(e) NULL)
  if (!is.null(OmegaCor)) for (r in seq_along(OmegaCor)) { write.csv(OmegaCor[[r]]$mean, file.path(resultDir, paste0('parameter_estimates_Omega_mean_', names(models)[j], '_', names(OmegaCor)[r], '.csv'))); if (requireNamespace('corrplot', quietly = TRUE)) try(corrplot::corrplot(OmegaCor[[r]]$mean, method='color'), silent=TRUE) }
}
dev.off()
