# run_this_HMSC_analysis.R -- generated by JSDMWorkbench
args <- commandArgs(trailingOnly = FALSE)
file_arg <- '--file='
script_arg <- args[startsWith(args, file_arg)]
if (length(script_arg) > 0) {
  script_path <- normalizePath(sub(file_arg, '', script_arg[[1]]), winslash = '/', mustWork = FALSE)
  setwd(dirname(dirname(script_path)))
}
source(file.path('reproducible_script', 'run_all_HMSC_S1_to_S7.R'))
