# run_all_HMSC_S1_to_S7.R -- generated by JSDMWorkbench
source('workflow_scripts/S1_define_models.R')
source('workflow_scripts/S2_fit_models.R')
source('workflow_scripts/S3_evaluate_convergence.R')
source('workflow_scripts/S4_compute_model_fit.R')
source('workflow_scripts/S5_show_model_fit.R')
source('workflow_scripts/S6_show_parameter_estimates.R')
source('workflow_scripts/S7_make_predictions.R')
