# Real boral adapter for JSDM Studio.
# boral itself requires the external JAGS system library through rjags/R2jags.

write_boral_result_workflow_map <- function(outdir) {
  dir.create(file.path(outdir, "tables"), recursive = TRUE, showWarnings = FALSE)
  boral_files <- data.frame(
    Section = c(
      "Configuration", "Inputs", "JAGS model", "Model object", "MCMC samples",
      "Posterior summaries", "Ordination", "Residual diagnostics", "Coefficients",
      "Correlations", "Random effects", "Variable selection", "Prediction",
      "Fit / model comparison", "Diagnostics", "Report"
    ),
    Expected_file_or_folder = c(
      "used_config.yml",
      "inputs/Y.csv, XData.csv, traits.csv, row.ids.csv, ranef.ids.csv, distmat.csv, offset.csv, newdata.csv, trial.size.csv",
      "jags/jagsboralmodel.txt",
      "models/boral_model.rds",
      "mcmc/mcmc_samples.rds, mcmc/mcmc_samples_summary.csv",
      "tables/summary_boral.txt, tables/summary_boral.csv, tables/hpd_intervals.csv, tables/tidyboral.csv",
      "ordination/lvsplot.pdf, ordination/lv_scores.csv, ordination/species_loadings.csv",
      "residuals/dunn_smyth_residuals.csv, plots/residual_diagnostics.pdf",
      "tables/coefficient_medians.csv, tables/coefficient_hpd.csv, plots/coefsplot.pdf",
      "tables/enviro_cor.csv, tables/residual_cor.csv",
      "random_effects/ranef_predictions.csv, random_effects/ranef_sigma.csv, plots/ranefsplot.pdf",
      "variable_selection/ssvs_posterior_probabilities.csv, variable_selection/trait_ssvs_probabilities.csv",
      "predictions/predictions.csv, predictions/fitted_values.csv",
      "tables/dic.csv, tables/logLik_conditional.csv, tables/logLik_marginal.csv, tables/measures.csv, tables/varpart.csv",
      "diagnostics/engine_status.json, diagnostics/data_check_messages.csv, diagnostics/JAGS_status.txt, diagnostics/boral_dependency_error.txt",
      "report/boral_report.html"
    ),
    Meaning = c(
      "Exact boral settings used for the run.",
      "Copied response, covariate, trait, random-effect, distance, offset and prediction inputs.",
      "Generated JAGS script used by boral for MCMC fitting.",
      "Serialized fitted boral object when fitting completes.",
      "Raw posterior samples from get.mcmcsamples for post-hoc diagnostics.",
      "Printed summary, posterior medians, HPD intervals and tidy posterior summaries.",
      "Latent-variable ordination scores and species loadings where available.",
      "Residual checking outputs from plot.boral and Dunn-Smyth residuals where available.",
      "Environmental/covariate coefficient summaries and coefficient plots.",
      "Species correlations due to environmental responses and residual latent variables.",
      "Response-specific random intercept predictions and variance components.",
      "Posterior inclusion probabilities from SSVS on X or traits.",
      "Predicted and fitted values from predict.boral and fitted.boral.",
      "DIC, log-likelihood, measures and variance-partitioning outputs where requested.",
      "Machine-readable status, warnings, errors, data checks and JAGS diagnostics.",
      "HTML report for browser viewing."
    ),
    stringsAsFactors = FALSE
  )
  write.csv(boral_files, file.path(outdir, "tables", "boral_result_workflow_map.csv"), row.names = FALSE)
  invisible(boral_files)
}

write_boral_reproducible_script <- function(outdir) {
  dir.create(file.path(outdir, "reproducible_script"), recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(outdir, "workflow_scripts"), recursive = TRUE, showWarnings = FALSE)
  write_boral_result_workflow_map(outdir)
  script <- r"{
# Reproducible boral 2.0.3 analysis script generated by JSDM Studio
# Run from the output folder with: Rscript reproducible_script/run_this_boral_analysis.R
args <- commandArgs(trailingOnly = FALSE)
file_arg <- "--file="
script_arg <- args[startsWith(args, file_arg)]
if (length(script_arg) > 0) {
  script_path <- normalizePath(sub(file_arg, "", script_arg[[1]]), winslash = "/", mustWork = FALSE)
  setwd(dirname(dirname(script_path)))
}

`%||%` <- function(x, y) {
  if (is.null(x) || length(x) == 0) return(y)
  if (length(x) == 1 && is.atomic(x) && is.na(x)) return(y)
  x
}
dirs <- c(
  "inputs", "data", "models", "results", "tables", "plots", "diagnostics",
  "report", "predictions", "reproducible_script", "standard", "workflow_scripts",
  "jags", "mcmc", "ordination", "residuals", "random_effects", "variable_selection"
)
for (d in dirs) dir.create(d, recursive = TRUE, showWarnings = FALSE)

status <- list(engine = "boral", status = "running", runtime_seconds = 0,
               warnings = character(), errors = character())
start_time <- Sys.time()

set_status_value <- function(value) {
  status <<- modifyList(status, list(status = value))
}
set_runtime_seconds <- function(value) {
  status <<- modifyList(status, list(runtime_seconds = value))
}
add_status_warning <- function(value) {
  status <<- modifyList(status, list(warnings = c(status$warnings %||% character(), value)))
}
add_status_error <- function(value) {
  status <<- modifyList(status, list(errors = c(status$errors %||% character(), value)))
}

write_lines <- function(x, path) writeLines(as.character(x), path, useBytes = TRUE)

safe_csv <- function(path) {
  if (!file.exists(path)) return(NULL)
  dat <- tryCatch(read.csv(path, check.names = FALSE, stringsAsFactors = FALSE), error = function(e) NULL)
  if (is.null(dat)) return(NULL)
  if (ncol(dat) > 1) {
    first <- dat[[1]]
    first_name <- names(dat)[1] %||% ""
    looks_like_row_index <- !nzchar(first_name) || first_name %in% c("X", "...1")
    if (!anyDuplicated(first) && (looks_like_row_index || !all(suppressWarnings(!is.na(as.numeric(first)))))) {
      dat <- dat[-1]
      rownames(dat) <- first
    }
  }
  dat
}

clean_predictors <- function(df) {
  if (is.null(df)) return(NULL)
  df <- as.data.frame(df, stringsAsFactors = FALSE, check.names = FALSE)
  for (nm in names(df)) {
    if (is.character(df[[nm]])) {
      x <- trimws(df[[nm]])
      numeric_x <- suppressWarnings(as.numeric(x))
      if (all(is.na(x) | !nzchar(x) | !is.na(numeric_x))) {
        df[[nm]] <- numeric_x
      } else {
        df[[nm]] <- as.factor(x)
      }
    } else if (is.logical(df[[nm]])) {
      df[[nm]] <- as.factor(df[[nm]])
    }
  }
  df
}

numeric_matrix <- function(df, label) {
  if (is.null(df)) stop(label, " is missing.", call. = FALSE)
  raw <- as.matrix(df)
  vals <- suppressWarnings(as.numeric(raw))
  mat <- matrix(vals, nrow = nrow(raw), ncol = ncol(raw), dimnames = dimnames(raw))
  raw_chr <- trimws(as.character(raw))
  bad <- !is.na(raw_chr) & nzchar(raw_chr) & is.na(vals)
  if (any(bad)) stop(label, " contains non-numeric values.", call. = FALSE)
  mat
}

id_matrix <- function(df) {
  if (is.null(df)) return(NULL)
  out <- as.data.frame(df, stringsAsFactors = FALSE, check.names = FALSE)
  for (nm in names(out)) out[[nm]] <- as.integer(as.factor(out[[nm]]))
  mat <- as.matrix(out)
  storage.mode(mat) <- "integer"
  mat
}

normalize_family <- function(x) {
  x <- tolower(trimws(as.character(x)))
  x[x == "lognormal"] <- "lnormal"
  x
}

parse_family <- function(Y, cfg) {
  model <- cfg$model %||% list()
  txt <- trimws(model$family_vector_override %||% "")
  if (nzchar(txt)) {
    fam <- normalize_family(unlist(strsplit(txt, ",")))
  } else {
    fam <- normalize_family(model$family %||% "negative.binomial")
  }
  fam <- fam[nzchar(fam)]
  if (length(fam) == 1) fam <- rep(fam, ncol(Y))
  fam
}

normalize_lv_type <- function(x) {
  x <- trimws(as.character(x %||% "independent"))
  if (identical(x, "power.exponential")) x <- "powered.exponential"
  x
}

parse_numeric_vector <- function(x, default = NULL) {
  txt <- trimws(as.character(x %||% ""))
  if (!nzchar(txt)) return(default)
  vals <- suppressWarnings(as.numeric(trimws(unlist(strsplit(txt, ",")))))
  vals[is.finite(vals)]
}

make_design <- function(X, formula_text) {
  if (is.null(X)) return(NULL)
  formula_text <- trimws(formula_text %||% "~ .")
  if (!nzchar(formula_text)) formula_text <- "~ ."
  mm <- model.matrix(as.formula(formula_text), data = X)
  intercept <- which(colnames(mm) == "(Intercept)")
  if (length(intercept) > 0) mm <- mm[, -intercept, drop = FALSE]
  mm
}

parse_xind <- function(text, S, P) {
  txt <- trimws(text %||% "")
  if (!nzchar(txt) || is.null(P) || P == 0) return(NULL)
  rows <- strsplit(txt, ";", fixed = TRUE)[[1]]
  mat <- do.call(rbind, lapply(rows, function(r) {
    suppressWarnings(as.numeric(trimws(unlist(strsplit(r, ",")))))
  }))
  if (nrow(mat) == 1 && length(mat) == P) mat <- matrix(rep(mat, each = S), nrow = S, byrow = FALSE)
  if (length(mat) == S * P) mat <- matrix(as.numeric(mat), nrow = S, ncol = P, byrow = TRUE)
  if (!all(dim(mat) == c(S, P))) stop("X.ind must be a 0/1 matrix with ncol(Y) rows and ncol(model.matrix(formula.X, X)) columns.", call. = FALSE)
  if (!all(mat %in% c(0, 1))) stop("X.ind values must be 0/1.", call. = FALSE)
  mat
}

parse_traits <- function(traits) {
  if (is.null(traits)) return(NULL)
  tr <- clean_predictors(traits)
  mm <- model.matrix(~ ., data = tr)
  intercept <- which(colnames(mm) == "(Intercept)")
  if (length(intercept) > 0) mm <- mm[, -intercept, drop = FALSE]
  if (ncol(mm) == 0) stop("traits.csv produced zero usable trait columns after encoding.", call. = FALSE)
  mm
}

parse_which_traits <- function(text, n_traits, n_x) {
  if (is.null(n_traits) || n_traits < 1) return(NULL)
  txt <- trimws(text %||% "")
  if (!nzchar(txt)) return(rep(list(seq_len(n_traits)), n_x + 1))
  groups <- strsplit(txt, ";", fixed = TRUE)[[1]]
  out <- lapply(groups, function(g) {
    vals <- suppressWarnings(as.integer(trimws(unlist(strsplit(g, ",")))))
    vals[is.finite(vals)]
  })
  if (length(out) == 1 && length(out[[1]]) > 0) out <- rep(out, n_x + 1)
  if (length(out) != n_x + 1) stop("which.traits must contain 1+ncol(X) semicolon-separated groups.", call. = FALSE)
  out
}

parse_ssvs_index <- function(text, use_ssvs, n_x) {
  if (!isTRUE(use_ssvs) || is.null(n_x) || n_x == 0) return(-1)
  vals <- suppressWarnings(as.integer(parse_numeric_vector(text, default = 0)))
  if (length(vals) == 0) vals <- 0
  if (length(vals) == 1) vals <- rep(vals, n_x)
  if (length(vals) != n_x) stop("prior.control$ssvs.index must have length 1 or ncol(X).", call. = FALSE)
  vals
}

parse_ssvs_traitsindex <- function(text, use_ssvs, which_traits) {
  if (!isTRUE(use_ssvs) || is.null(which_traits)) return(-1)
  txt <- trimws(text %||% "")
  if (!nzchar(txt)) {
    return(lapply(which_traits, function(z) if (length(z) == 1 && z[[1]] == 0) -1L else rep(0L, length(z))))
  }
  groups <- strsplit(txt, ";", fixed = TRUE)[[1]]
  out <- lapply(groups, function(g) {
    vals <- suppressWarnings(as.integer(trimws(unlist(strsplit(g, ",")))))
    vals[is.finite(vals)]
  })
  if (length(out) != length(which_traits)) stop("prior.control$ssvs.traitsindex must match which.traits length.", call. = FALSE)
  out
}

parse_trial_size <- function(trials, scalar, S) {
  if (is.null(trials)) {
    val <- suppressWarnings(as.numeric(scalar %||% 1))
    if (!is.finite(val) || val < 1) stop("trial.size must be positive.", call. = FALSE)
    return(val)
  }
  mat <- numeric_matrix(trials, "trial.size.csv")
  vals <- as.numeric(mat)
  vals <- vals[is.finite(vals)]
  if (length(vals) == 1) return(vals)
  if (length(vals) == S) return(vals)
  if (ncol(mat) == S) {
    per_col <- apply(mat, 2, function(z) unique(z[is.finite(z)]))
    if (all(vapply(per_col, length, integer(1)) == 1)) return(as.numeric(per_col))
  }
  stop("trial.size.csv must contain one value or one value per response/species.", call. = FALSE)
}

flatten_matrix <- function(x, value_name = "value") {
  if (is.null(x)) return(data.frame())
  if (is.list(x) && !is.data.frame(x)) {
    if (!is.null(x$out)) return(flatten_matrix(x$out, value_name = value_name))
    parts <- lapply(names(x), function(nm) {
      if (is.null(x[[nm]])) return(NULL)
      dat <- flatten_matrix(x[[nm]], value_name = value_name)
      if (!nrow(dat)) return(NULL)
      data.frame(component = nm, dat, stringsAsFactors = FALSE)
    })
    parts <- Filter(Negate(is.null), parts)
    if (length(parts) == 0) return(data.frame())
    all_names <- unique(unlist(lapply(parts, names)))
    parts <- lapply(parts, function(dat) {
      missing <- setdiff(all_names, names(dat))
      for (nm in missing) dat[[nm]] <- NA
      dat[, all_names, drop = FALSE]
    })
    return(do.call(rbind, parts))
  }
  if (is.data.frame(x)) return(x)
  if (is.vector(x) && is.null(dim(x))) {
    return(data.frame(name = names(x) %||% seq_along(x), value = as.numeric(x), stringsAsFactors = FALSE))
  }
  arr <- as.array(x)
  idx <- as.data.frame.table(arr, responseName = value_name, stringsAsFactors = FALSE)
  idx
}

write_status <- function() {
  set_runtime_seconds(as.numeric(difftime(Sys.time(), start_time, units = "secs")))
  if (requireNamespace("jsonlite", quietly = TRUE)) {
    writeLines(jsonlite::toJSON(status, pretty = TRUE, auto_unbox = TRUE), file.path("diagnostics", "engine_status.json"))
  } else {
    capture.output(str(status), file = file.path("diagnostics", "engine_status.json"))
  }
  write.csv(data.frame(engine = status$engine, status = status$status,
                       message = paste(c(status$warnings, status$errors), collapse = "; "),
                       stringsAsFactors = FALSE),
            file.path("tables", "engine_status.csv"), row.names = FALSE)
  if (length(status$errors) > 0) writeLines(status$errors, file.path("diagnostics", "boral_error.txt"))
  writeLines(capture.output(sessionInfo()), file.path("diagnostics", "session_info.txt"))
}

write_standard <- function(Y = NULL, X = NULL) {
  write.csv(data.frame(
    run_id = basename(getwd()), engine = "boral", status = status$status,
    n_sites = if (is.null(Y)) NA_integer_ else nrow(Y),
    n_responses = if (is.null(Y)) NA_integer_ else ncol(Y),
    n_predictors = if (is.null(X)) NA_integer_ else ncol(X),
    stringsAsFactors = FALSE
  ), file.path("standard", "run_summary.csv"), row.names = FALSE)
  write.csv(data.frame(engine = "boral", response_id = NA_character_, predictor = NA_character_,
                       direction = NA_character_, estimate = NA_real_, lower = NA_real_, upper = NA_real_,
                       notes = status$status, stringsAsFactors = FALSE),
            file.path("standard", "effects_long.csv"), row.names = FALSE)
  write.csv(data.frame(engine = "boral", site_id = NA_character_, response_id = NA_character_,
                       observed = NA_real_, predicted_mean = NA_real_, predicted_lower = NA_real_,
                       predicted_upper = NA_real_, stringsAsFactors = FALSE),
            file.path("standard", "predictions_long.csv"), row.names = FALSE)
  write.csv(data.frame(engine = "boral", response_1 = NA_character_, response_2 = NA_character_,
                       association_type = NA_character_, estimate = NA_real_, comparable_level = status$status,
                       stringsAsFactors = FALSE),
            file.path("standard", "associations_long.csv"), row.names = FALSE)
  write.csv(data.frame(engine = "boral", metric = NA_character_, response_id = NA_character_,
                       value = NA_real_, notes = status$status, stringsAsFactors = FALSE),
            file.path("standard", "fit_metrics.csv"), row.names = FALSE)
}

write_report <- function(extra = "") {
  files <- list.files(".", recursive = TRUE)
  html <- c(
    "<!doctype html><html><head><meta charset='utf-8'><title>boral report</title>",
    "<style>body{font-family:Arial,sans-serif;margin:32px;color:#172033}code{background:#f1f5f9;padding:2px 5px;border-radius:4px}table{border-collapse:collapse}td,th{border:1px solid #d7dee8;padding:6px 8px}</style>",
    "</head><body>",
    "<h1>boral workflow report</h1>",
    paste0("<p>Status: <b>", status$status, "</b></p>"),
    paste0("<p>", extra, "</p>"),
    "<p>Start with <code>diagnostics/engine_status.json</code>, <code>diagnostics/data_check_messages.csv</code> and <code>standard/run_summary.csv</code>.</p>",
    "<h2>Output files</h2><pre>",
    paste(utils::head(files, 200), collapse = "\n"),
    "</pre></body></html>"
  )
  writeLines(html, file.path("report", "boral_report.html"), useBytes = TRUE)
}

write_empty_readmes <- function() {
  for (d in dirs) {
    if (dir.exists(d) && length(list.files(d, all.files = FALSE, no.. = TRUE)) == 0) {
      writeLines(c("boral output folder", paste0("Status: ", status$status),
                   "No engine-specific file was produced here for the current settings/status."),
                 file.path(d, "README.txt"))
    }
  }
}

safe_step <- function(label, expr) {
  tryCatch(expr, error = function(e) {
    msg <- paste0(label, " failed: ", conditionMessage(e))
    add_status_warning(msg)
    writeLines(msg, file.path("diagnostics", paste0(gsub("[^A-Za-z0-9]+", "_", label), "_warning.txt")))
    NULL
  })
}

cfg <- if (requireNamespace("yaml", quietly = TRUE) && file.exists("used_config.yml")) yaml::read_yaml("used_config.yml") else list()
Y <- safe_csv(file.path("data", "Y.csv")) %||% safe_csv(file.path("inputs", "Y.csv"))
X_raw <- safe_csv(file.path("data", "XData.csv")) %||% safe_csv(file.path("inputs", "XData.csv"))
traits_raw <- safe_csv(file.path("data", "traits.csv")) %||% safe_csv(file.path("inputs", "traits.csv"))
rowids_raw <- safe_csv(file.path("data", "row.ids.csv")) %||% safe_csv(file.path("inputs", "row.ids.csv"))
ranefids_raw <- safe_csv(file.path("data", "ranef.ids.csv")) %||% safe_csv(file.path("inputs", "ranef.ids.csv"))
distmat_raw <- safe_csv(file.path("data", "distmat.csv")) %||% safe_csv(file.path("inputs", "distmat.csv"))
offset_raw <- safe_csv(file.path("data", "offset.csv")) %||% safe_csv(file.path("inputs", "offset.csv"))
newdata_raw <- safe_csv(file.path("data", "newdata.csv")) %||% safe_csv(file.path("inputs", "newdata.csv"))
trials_raw <- safe_csv(file.path("data", "trial.size.csv")) %||% safe_csv(file.path("inputs", "trial.size.csv"))

model_cfg <- cfg$model %||% list()
trait_cfg <- cfg$traits_random_ssvs %||% list()
mcmc_cfg <- cfg$mcmc_prior %||% list()
diag_cfg <- cfg$diagnostics_outputs %||% list()
out_cfg <- cfg$outputs %||% list()

fit_or_fail <- tryCatch({
  if (is.null(Y)) stop("Y.csv is required.", call. = FALSE)
  Ymat <- numeric_matrix(Y, "Y.csv")
  X_clean <- clean_predictors(X_raw)
  X_design <- make_design(X_clean, model_cfg$formula.X %||% "~ .")
  fam <- parse_family(Ymat, cfg)
  allowed <- c("negative.binomial", "ztnegative.binomial", "poisson", "ztpoisson", "binomial",
               "normal", "lnormal", "tweedie", "ordinal", "exponential", "gamma", "beta")
  bad <- setdiff(fam, allowed)
  if (length(bad) > 0) stop("Unsupported boral family value(s): ", paste(unique(bad), collapse = ", "), call. = FALSE)
  if (length(fam) != ncol(Ymat)) stop("Family vector must have length one or ncol(Y).", call. = FALSE)
  trial_size <- parse_trial_size(trials_raw, model_cfg$trial.size %||% 1, ncol(Ymat))
  for (j in seq_len(ncol(Ymat))) {
    yj <- Ymat[, j]
    fj <- fam[[j]]
    if (fj == "binomial") {
      tj <- if (length(trial_size) == 1) trial_size else trial_size[[j]]
      if (any(yj < 0 | abs(yj - round(yj)) > 1e-8 | yj > tj, na.rm = TRUE)) stop("binomial Y must be integer successes between 0 and trial.size.", call. = FALSE)
    }
    if (fj %in% c("poisson", "negative.binomial") && any(yj < 0 | abs(yj - round(yj)) > 1e-8, na.rm = TRUE)) stop(fj, " responses must be non-negative integers.", call. = FALSE)
    if (fj %in% c("ztpoisson", "ztnegative.binomial") && any(yj < 1 | abs(yj - round(yj)) > 1e-8, na.rm = TRUE)) stop(fj, " responses must be positive integers.", call. = FALSE)
    if (fj %in% c("beta") && any(yj <= 0 | yj >= 1, na.rm = TRUE)) stop("beta responses must be strictly between 0 and 1.", call. = FALSE)
    if (fj %in% c("gamma", "exponential", "lnormal") && any(yj <= 0, na.rm = TRUE)) stop(fj, " responses must be positive.", call. = FALSE)
    if (fj == "ordinal" && any(yj < 1 | abs(yj - round(yj)) > 1e-8, na.rm = TRUE)) stop("ordinal responses must be positive integer levels.", call. = FALSE)
  }
  if (!is.null(X_clean) && nrow(X_clean) != nrow(Ymat)) stop("XData.csv rows must match Y.csv rows.", call. = FALSE)
  if (!is.null(newdata_raw)) {
    new_clean <- clean_predictors(newdata_raw)
    missing_new <- setdiff(names(X_clean %||% data.frame()), names(new_clean))
    if (length(missing_new) > 0) stop("newdata.csv is missing XData columns: ", paste(missing_new, collapse = ", "), call. = FALSE)
  }
  lv_type <- normalize_lv_type((model_cfg$lv.control %||% list())$type %||% "independent")
  num_lv <- as.integer((model_cfg$lv.control %||% list())$num.lv %||% 0)
  if (!is.finite(num_lv) || num_lv < 0) stop("num.lv must be >= 0.", call. = FALSE)
  distmat <- if (!is.null(distmat_raw)) numeric_matrix(distmat_raw, "distmat.csv") else NULL
  if (lv_type != "independent") {
    if (is.null(distmat)) stop("Structured latent variables require distmat.csv.", call. = FALSE)
    if (!all(dim(distmat) == c(nrow(Ymat), nrow(Ymat)))) stop("distmat.csv must be nrow(Y) by nrow(Y).", call. = FALSE)
  }
  lv_control <- list(num.lv = num_lv, type = lv_type, distmat = distmat)
  if (num_lv == 0) lv_control$type <- "independent"
  rowids <- id_matrix(rowids_raw)
  ranefids <- if (isTRUE(trait_cfg$use_ranef %||% FALSE)) id_matrix(ranefids_raw) else NULL
  if (!is.null(rowids) && nrow(rowids) != nrow(Ymat)) stop("row.ids.csv rows must match Y.csv rows.", call. = FALSE)
  if (!is.null(ranefids) && nrow(ranefids) != nrow(Ymat)) stop("ranef.ids.csv rows must match Y.csv rows.", call. = FALSE)
  offset <- if (isTRUE(model_cfg$use_offset %||% FALSE)) numeric_matrix(offset_raw, "offset.csv") else NULL
  if (!is.null(offset) && !all(dim(offset) == dim(Ymat))) stop("offset.csv must have the same dimensions as Y.csv.", call. = FALSE)
  traits <- if (isTRUE(trait_cfg$use_traits %||% FALSE)) parse_traits(traits_raw) else NULL
  if (!is.null(traits) && nrow(traits) != ncol(Ymat)) stop("traits.csv rows must match Y.csv columns/species.", call. = FALSE)
  which_traits <- parse_which_traits(trait_cfg$which.traits %||% "", if (is.null(traits)) NULL else ncol(traits), if (is.null(X_design)) 0 else ncol(X_design))
  ssvs_index <- parse_ssvs_index(trait_cfg$ssvs.index %||% "", isTRUE(trait_cfg$use_ssvs %||% FALSE) && is.null(traits), if (is.null(X_design)) 0 else ncol(X_design))
  ssvs_traitsindex <- parse_ssvs_traitsindex(trait_cfg$ssvs.traitsindex %||% "", isTRUE(trait_cfg$use_ssvs %||% FALSE) && !is.null(traits), which_traits)
  prior_type <- trimws(unlist(strsplit(mcmc_cfg$prior.type %||% "normal,normal,normal,uniform", ",")))
  hypparams <- suppressWarnings(as.numeric(trimws(unlist(strsplit(mcmc_cfg$hypparams %||% "10,10,10,30", ",")))))
  if (length(prior_type) != 4 || length(hypparams) != 4 || any(!is.finite(hypparams))) stop("prior.control$type and hypparams must each have four values.", call. = FALSE)
  mcmc_control <- list(
    n.burnin = as.integer(mcmc_cfg$n.burnin %||% 10000),
    n.iteration = as.integer(mcmc_cfg$n.iteration %||% 40000),
    n.thin = as.integer(mcmc_cfg$n.thin %||% 30),
    seed = as.integer(mcmc_cfg$seed %||% 1234)
  )
  prior_control <- list(type = prior_type, hypparams = hypparams,
                        ssvs.index = ssvs_index, ssvs.g = as.numeric(trait_cfg$ssvs.g %||% 1e-6),
                        ssvs.traitsindex = ssvs_traitsindex)
  write.csv(data.frame(response = colnames(Ymat), family = fam, trial_size = if (length(trial_size) == 1) trial_size else trial_size,
                       stringsAsFactors = FALSE), file.path("tables", "family_trial_size.csv"), row.names = FALSE)
  if (!is.null(X_design)) write.csv(X_design, file.path("data", "X_design_matrix.csv"), row.names = TRUE)
  if (!is.null(traits)) write.csv(traits, file.path("data", "traits_design_matrix.csv"), row.names = TRUE)

  dep_errors <- character()
  if (!requireNamespace("rjags", quietly = TRUE)) {
    dep_errors <- c(dep_errors, "R package rjags is not available.")
  } else {
    rjags_load <- tryCatch({ suppressPackageStartupMessages(library(rjags)); TRUE },
                           error = function(e) conditionMessage(e))
    if (!isTRUE(rjags_load)) dep_errors <- c(dep_errors, paste0("rjags cannot load JAGS: ", rjags_load))
  }
  if (!requireNamespace("R2jags", quietly = TRUE)) dep_errors <- c(dep_errors, "R package R2jags is not available.")
  if (!requireNamespace("boral", quietly = TRUE)) dep_errors <- c(dep_errors, "R package boral is not installed or cannot load.")
  writeLines(if (length(dep_errors) == 0) "JAGS/rjags/R2jags/boral dependency check passed." else dep_errors,
             file.path("diagnostics", "JAGS_status.txt"))
  if (length(dep_errors) > 0) {
    set_status_value("fit_failed")
    add_status_error(dep_errors)
    writeLines(dep_errors, file.path("diagnostics", "boral_dependency_error.txt"))
    dep_notes <- rep("", 4)
    dep_notes[seq_len(min(4, length(dep_errors)))] <- dep_errors[seq_len(min(4, length(dep_errors)))]
    write.csv(data.frame(parameter = c("boral", "rjags", "R2jags", "JAGS"), status = "missing_or_unloadable",
                         notes = dep_notes, stringsAsFactors = FALSE),
              file.path("diagnostics", "dependency_status.csv"), row.names = FALSE)
    stop(paste(dep_errors, collapse = "; "), call. = FALSE)
  }

  fam_arg <- if (length(unique(fam)) == 1) unique(fam) else fam
  formula_arg <- if (!is.null(X_clean)) as.formula(trimws(model_cfg$formula.X %||% "~ .")) else NULL
  X_arg <- if (!is.null(X_clean)) X_clean else NULL
  Xind <- parse_xind(model_cfg$X.ind %||% "", ncol(Ymat), if (is.null(X_design)) 0 else ncol(X_design))
  model_name <- basename(model_cfg$model.name %||% "jagsboralmodel.txt")
  if (!nzchar(model_name)) model_name <- "jagsboralmodel.txt"
  model_name <- file.path("jags", model_name)
  fit_args <- list(
    y = Ymat,
    X = X_arg,
    formula.X = formula_arg,
    X.ind = Xind,
    traits = traits,
    which.traits = which_traits,
    family = fam_arg,
    trial.size = trial_size,
    lv.control = lv_control,
    row.eff = model_cfg$row.eff %||% "none",
    row.ids = rowids,
    ranef.ids = ranefids,
    offset = offset,
    save.model = isTRUE(trait_cfg$save.model %||% FALSE) || isTRUE(mcmc_cfg$save_mcmc_samples %||% FALSE),
    calc.ics = isTRUE(mcmc_cfg$calc.ics %||% FALSE),
    mcmc.control = mcmc_control,
    prior.control = prior_control,
    do.fit = isTRUE(model_cfg$do.fit %||% TRUE),
    model.name = model_name
  )
  fit_args <- fit_args[!vapply(fit_args, is.null, logical(1))]
  capture.output(str(fit_args, max.level = 2), file = file.path("diagnostics", "boral_fit_arguments.txt"))
  suppressPackageStartupMessages(library(boral))
  fit <- do.call(boral::boral, fit_args)
  if (isTRUE(out_cfg$save_model %||% TRUE)) saveRDS(fit, file.path("models", "boral_model.rds"))
  if (file.exists(model_name) && isTRUE(out_cfg$save_jags %||% TRUE)) {
    jags_dest <- file.path("jags", "jagsboralmodel.txt")
    if (!identical(normalizePath(model_name, winslash = "/", mustWork = FALSE),
                   normalizePath(jags_dest, winslash = "/", mustWork = FALSE))) {
      file.copy(model_name, jags_dest, overwrite = TRUE)
    }
  }
  if (!isTRUE(model_cfg$do.fit %||% TRUE)) {
    writeLines(c(
      "boral model was defined with do.fit=FALSE.",
      "JAGS model code and the boral model definition were exported; posterior summaries are intentionally skipped."
    ), file.path("results", "MODEL_DEFINED_NOT_FITTED.txt"))
    set_status_value("model_defined")
    TRUE
  } else {
  if (isTRUE(diag_cfg$summary %||% TRUE)) {
    capture.output(print(summary(fit)), file = file.path("tables", "summary_boral.txt"))
    summ <- safe_step("summary.boral", summary(fit))
    if (!is.null(summ)) {
      capture.output(str(summ), file = file.path("tables", "summary_boral_structure.txt"))
    }
  }
  safe_step("tidyboral", {
    if (isTRUE(diag_cfg$tidyboral %||% TRUE) && exists("tidyboral", where = asNamespace("boral"), inherits = FALSE)) {
      tb <- boral::tidyboral(fit)
      saveRDS(tb, file.path("tables", "tidyboral.rds"))
      capture.output(str(tb), file = file.path("tables", "tidyboral_structure.txt"))
    }
  })
  safe_step("hpd intervals", {
    if (isTRUE(mcmc_cfg$save_hpd %||% TRUE) && !is.null(fit$hpdintervals)) {
      saveRDS(fit$hpdintervals, file.path("tables", "hpd_intervals.rds"))
      capture.output(str(fit$hpdintervals), file = file.path("tables", "hpd_intervals_structure.txt"))
    } else {
      write.csv(data.frame(output = "hpd_intervals", status = "not_available_for_this_model_or_settings", stringsAsFactors = FALSE),
                file.path("tables", "hpd_intervals_manifest.csv"), row.names = FALSE)
    }
  })
  safe_step("mcmc samples", {
    if (isTRUE(mcmc_cfg$save_mcmc_samples %||% TRUE) && exists("get.mcmcsamples", where = asNamespace("boral"), inherits = FALSE)) {
      smp <- boral::get.mcmcsamples(fit)
      saveRDS(smp, file.path("mcmc", "mcmc_samples.rds"))
      capture.output(summary(smp), file = file.path("mcmc", "mcmc_samples_summary.txt"))
    } else if (!is.null(fit$fit.mcmc)) {
      saveRDS(fit$fit.mcmc, file.path("mcmc", "mcmc_samples.rds"))
    }
  })
  safe_step("fitted values", {
    if (isTRUE(diag_cfg$fitted %||% TRUE)) {
      fv <- boral::fitted.boral(fit)
      write.csv(flatten_matrix(fv, "fitted"), file.path("predictions", "fitted_values.csv"), row.names = FALSE)
      write.csv(flatten_matrix(fv, "predicted_mean"), file.path("standard", "predictions_long.csv"), row.names = FALSE)
    }
  })
  safe_step("predictions", {
    if (isTRUE(diag_cfg$predict %||% TRUE)) {
      new_clean <- clean_predictors(newdata_raw)
      if (!is.null(new_clean)) {
        new_design <- make_design(new_clean, model_cfg$formula.X %||% "~ .")
        can_new_predict <- !is.null(new_design) &&
          (fit$lv.control$type %||% "independent") == "independent" &&
          (fit$row.eff %||% "none") == "none" &&
          is.null(fit$ranef.ids)
        if (isTRUE(can_new_predict)) {
          pr <- boral::predict.boral(fit, newX = new_design, predict.type = "marginal", scale = "response")
          saveRDS(pr, file.path("predictions", "predictions.rds"))
          write.csv(flatten_matrix(pr, "predicted"), file.path("predictions", "predictions.csv"), row.names = FALSE)
        } else {
          write.csv(data.frame(output = "newdata_predictions", status = "skipped_requires_new_latent_distance_or_random_effect_ids", stringsAsFactors = FALSE),
                    file.path("predictions", "prediction_manifest.csv"), row.names = FALSE)
        }
      } else {
        pr <- boral::predict.boral(fit, scale = "response")
        saveRDS(pr, file.path("predictions", "predictions.rds"))
        write.csv(flatten_matrix(pr, "predicted"), file.path("predictions", "predictions.csv"), row.names = FALSE)
      }
    }
  })
  safe_step("enviro_cor", {
    if (isTRUE(diag_cfg$enviro_cor %||% TRUE) && exists("get.enviro.cor", where = asNamespace("boral"), inherits = FALSE) && !is.null(fit$X.coefs.mean)) {
      ec <- boral::get.enviro.cor(fit)
      write.csv(flatten_matrix(ec, "correlation"), file.path("tables", "enviro_cor.csv"), row.names = FALSE)
    } else if (isTRUE(diag_cfg$enviro_cor %||% TRUE)) {
      write.csv(data.frame(output = "enviro_cor", status = "not_available_without_X_coefficients", stringsAsFactors = FALSE),
                file.path("tables", "enviro_cor_manifest.csv"), row.names = FALSE)
    }
  })
  safe_step("residual_cor", {
    if (isTRUE(diag_cfg$residual_cor %||% TRUE) && exists("get.residual.cor", where = asNamespace("boral"), inherits = FALSE) && (fit$num.lv %||% 0) > 0) {
      rc <- boral::get.residual.cor(fit)
      write.csv(flatten_matrix(rc, "correlation"), file.path("tables", "residual_cor.csv"), row.names = FALSE)
      assoc <- flatten_matrix(rc, "estimate")
      write.csv(data.frame(engine = "boral", assoc, association_type = "residual_latent_variable", stringsAsFactors = FALSE),
                file.path("standard", "associations_long.csv"), row.names = FALSE)
    } else if (isTRUE(diag_cfg$residual_cor %||% TRUE)) {
      write.csv(data.frame(output = "residual_cor", status = "not_available_without_latent_variables", stringsAsFactors = FALSE),
                file.path("tables", "residual_cor_manifest.csv"), row.names = FALSE)
    }
  })
  safe_step("DIC", {
    if (isTRUE(mcmc_cfg$save_dic %||% TRUE) && !is.null(fit$dic)) {
      write.csv(flatten_matrix(fit$dic, "value"), file.path("tables", "dic.csv"), row.names = FALSE)
    }
    if (!is.null(fit$logLik)) write.csv(flatten_matrix(fit$logLik, "value"), file.path("tables", "logLik_conditional.csv"), row.names = FALSE)
    if (!is.null(fit$measures)) write.csv(flatten_matrix(fit$measures, "value"), file.path("tables", "measures.csv"), row.names = FALSE)
  })
  safe_step("variance partition", {
    if (isTRUE(diag_cfg$varpart %||% FALSE) && exists("calc.varpart", where = asNamespace("boral"), inherits = FALSE)) {
      vp <- boral::calc.varpart(fit)
      saveRDS(vp, file.path("tables", "varpart.rds"))
      write.csv(flatten_matrix(vp, "value"), file.path("tables", "varpart.csv"), row.names = FALSE)
    }
  })
  safe_step("plots", {
    if (isTRUE(out_cfg$save_plots %||% TRUE)) {
      if (isTRUE(diag_cfg$residual_plot %||% TRUE)) {
        grDevices::pdf(file.path("plots", "residual_diagnostics.pdf")); try(plot(fit), silent = TRUE); grDevices::dev.off()
      }
      if (isTRUE(diag_cfg$lvsplot %||% TRUE) && num_lv > 0) {
        grDevices::pdf(file.path("ordination", "lvsplot.pdf")); try(boral::lvsplot(fit), silent = TRUE); grDevices::dev.off()
      }
      if (isTRUE(diag_cfg$coefsplot %||% TRUE)) {
        grDevices::pdf(file.path("plots", "coefsplot.pdf")); try(boral::coefsplot(fit), silent = TRUE); grDevices::dev.off()
      }
      if (isTRUE(diag_cfg$ranefsplot %||% FALSE) && !is.null(ranefids)) {
        grDevices::pdf(file.path("plots", "ranefsplot.pdf")); try(boral::ranefsplot(fit), silent = TRUE); grDevices::dev.off()
      }
    }
  })
  safe_step("direct object tables", {
    direct_names <- c("X.coefs.median", "X.coefs.mean", "lv.coefs.median", "lv.mean", "traits.coefs.median",
                      "row.coefs", "row.sigma", "ranef.coefs.median", "ranef.sigma.median",
                      "ssvs.indcoefs.mean", "ssvs.traitscoefs.mean")
    for (nm in direct_names) {
      if (!is.null(fit[[nm]])) {
        target_dir <- if (grepl("row|ranef", nm)) "random_effects" else if (grepl("ssvs", nm)) "variable_selection" else if (grepl("lv", nm)) "ordination" else "tables"
        saveRDS(fit[[nm]], file.path(target_dir, paste0(nm, ".rds")))
        capture.output(str(fit[[nm]]), file = file.path(target_dir, paste0(nm, "_structure.txt")))
      }
    }
  })
  set_status_value("fitted")
  }
  TRUE
}, error = function(e) {
  set_status_value("fit_failed")
  if (length(status$errors %||% character()) == 0) add_status_error(conditionMessage(e))
  writeLines(conditionMessage(e), file.path("diagnostics", "boral_fit_error.txt"))
  FALSE
})

write.csv(data.frame(
  Section = c("Configuration", "Inputs", "JAGS model", "Model object", "MCMC samples", "Posterior summaries", "Ordination", "Residual diagnostics", "Coefficients", "Correlations", "Random effects", "Variable selection", "Prediction", "Fit / model comparison", "Diagnostics", "Report"),
  Expected_file_or_folder = c("used_config.yml", "inputs/data copies", "jags/jagsboralmodel.txt", "models/boral_model.rds", "mcmc/mcmc_samples.rds", "tables/summary_boral.*", "ordination/*", "residuals/* and plots/residual_diagnostics.pdf", "tables/coefficient_* and plots/coefsplot.pdf", "tables/*cor.csv", "random_effects/*", "variable_selection/*", "predictions/*", "tables/dic.csv/logLik/measures/varpart", "diagnostics/*", "report/boral_report.html"),
  stringsAsFactors = FALSE
), file.path("tables", "boral_result_workflow_map.csv"), row.names = FALSE)

write_standard(Y, X_raw)
write_status()
write_report(if (status$status == "fit_failed") paste(c(status$warnings, status$errors), collapse = "; ") else "boral run completed or model was defined.")
write.csv(data.frame(file = list.files(".", recursive = TRUE), stringsAsFactors = FALSE),
          file.path("standard", "output_manifest.csv"), row.names = FALSE)
write_empty_readmes()

if (!fit_or_fail) quit(status = 1)
}"
  writeLines(strsplit(script, "\n", fixed = TRUE)[[1]],
             file.path(outdir, "reproducible_script", "run_this_boral_analysis.R"), useBytes = TRUE)
  writeLines(c(
    "# Workflow wrapper for boral",
    "source(file.path('reproducible_script', 'run_this_boral_analysis.R'))"
  ), file.path(outdir, "workflow_scripts", "run_boral_workflow.R"), useBytes = TRUE)
  invisible(file.path(outdir, "reproducible_script", "run_this_boral_analysis.R"))
}
